#!/bin/bash
# Paper configurations. Usage: bash scripts/lastopd/cells.sh <cell>
#   Env you must set: DATA_DIR OUT_DIR MODEL_DIR (contains the HF model folders below)
# Same-architecture pair (Table: JustRL-DeepSeek-1.5B -> DeepSeek-R1-Distill-Qwen-1.5B):
#   lastopd        LastOPD (ours): last-layer latent loss on all response tokens + token loss, crossfade 10/10
#   lastopd_always LastOPD-always: same, no crossfade (both terms always on)
#   vanilla        OPRD-Vanilla:   all-layer latent loss on the last 250 response tokens, latent only
#   vanilla_token  OPRD-Vanilla + token loss
# Cross-size pairs (Qwen3-4B / Qwen3-8B -> Qwen3-1.7B-Base): q4_lastopd q4_lastopd_always q8_lastopd q8_lastopd_always
set -euo pipefail
CELL=${1:?cell}
MODEL_DIR=${MODEL_DIR:?set MODEL_DIR}
S=$(dirname "${BASH_SOURCE[0]}")
STU15=$MODEL_DIR/DeepSeek-R1-Distill-Qwen-1.5B; TCH15=$MODEL_DIR/JustRL-DeepSeek-1.5B
STU17=$MODEL_DIR/Qwen3-1.7B-Base
case "$CELL" in
  lastopd)        ENV=(ACTOR_MODEL_PATH=$STU15 REWARD_MODEL_PATH=$TCH15 MODE=combined REP_DISTILLATION_LAYERS=last REP_DISTILLATION_POSITIONS=all REP_COEF_DECAY_STEPS=10 TOKEN_COEF_RAMP_STEPS=10) ;;
  lastopd_always) ENV=(ACTOR_MODEL_PATH=$STU15 REWARD_MODEL_PATH=$TCH15 MODE=combined REP_DISTILLATION_LAYERS=last REP_DISTILLATION_POSITIONS=all REP_COEF_DECAY_STEPS=0  TOKEN_COEF_RAMP_STEPS=0) ;;
  vanilla)        ENV=(ACTOR_MODEL_PATH=$STU15 REWARD_MODEL_PATH=$TCH15 MODE=rep_only REP_DISTILLATION_LAYERS=all REP_DISTILLATION_POSITIONS=last_k REP_DISTILLATION_LAST_K=250 REP_COEF_DECAY_STEPS=0 TOKEN_COEF_RAMP_STEPS=0 REP_TEACHER_CACHE_DTYPE=bf16) ;;
  vanilla_token)  ENV=(ACTOR_MODEL_PATH=$STU15 REWARD_MODEL_PATH=$TCH15 MODE=combined REP_DISTILLATION_LAYERS=all REP_DISTILLATION_POSITIONS=last_k REP_DISTILLATION_LAST_K=250 REP_COEF_DECAY_STEPS=0 TOKEN_COEF_RAMP_STEPS=0 REP_TEACHER_CACHE_DTYPE=bf16) ;;
  q4_lastopd)        ENV=(ACTOR_MODEL_PATH=$STU17 REWARD_MODEL_PATH=$MODEL_DIR/Qwen3-4B REPETITION_PENALTY=1.05 MODE=combined REP_DISTILLATION_LAYERS=last REP_DISTILLATION_POSITIONS=all REP_COEF_DECAY_STEPS=10 TOKEN_COEF_RAMP_STEPS=10 REP_TEACHER_CACHE_DTYPE=bf16) ;;
  q4_lastopd_always) ENV=(ACTOR_MODEL_PATH=$STU17 REWARD_MODEL_PATH=$MODEL_DIR/Qwen3-4B REPETITION_PENALTY=1.05 MODE=combined REP_DISTILLATION_LAYERS=last REP_DISTILLATION_POSITIONS=all REP_COEF_DECAY_STEPS=0  TOKEN_COEF_RAMP_STEPS=0  REP_TEACHER_CACHE_DTYPE=bf16) ;;
  q8_lastopd)        ENV=(ACTOR_MODEL_PATH=$STU17 REWARD_MODEL_PATH=$MODEL_DIR/Qwen3-8B REPETITION_PENALTY=1.05 MODE=combined REP_DISTILLATION_LAYERS=last REP_DISTILLATION_POSITIONS=all REP_COEF_DECAY_STEPS=10 TOKEN_COEF_RAMP_STEPS=10 REP_TEACHER_CACHE_DTYPE=bf16) ;;
  q8_lastopd_always) ENV=(ACTOR_MODEL_PATH=$STU17 REWARD_MODEL_PATH=$MODEL_DIR/Qwen3-8B REPETITION_PENALTY=1.05 MODE=combined REP_DISTILLATION_LAYERS=last REP_DISTILLATION_POSITIONS=all REP_COEF_DECAY_STEPS=0  TOKEN_COEF_RAMP_STEPS=0  REP_TEACHER_CACHE_DTYPE=bf16) ;;
  *) echo "unknown cell $CELL"; exit 1 ;;
esac
env "${ENV[@]}" REP_DISTILLATION_COEF=${REP_DISTILLATION_COEF:-1000} USE_KL_LOSS=False RUN_TAG=${RUN_TAG:-$CELL} bash "$S/train.sh"
